USE OBLIGATORIOBD1;

#1
SELECT E.cod_editorial, E.nom_editorial
FROM EDITORIALES E
INNER JOIN OBRA_EDITORIAL OE ON E.cod_editorial = OE.cod_editorial
INNER JOIN OBRAS O ON O.cod_obra = OE.cod_obra
WHERE O.paginas = (SELECT MAX(paginas) FROM OBRAS);

#2
SELECT A.nom_autor
FROM AUTORES A
INNER JOIN OBRA_AUTOR OA ON A.cod_autor = OA.cod_autor
INNER JOIN OBRAS O ON O.cod_obra = OA.cod_obra
INNER JOIN OBRA_TEMA OT ON O.cod_obra = OT.cod_obra
INNER JOIN TEMAS T ON T.cod_tema = OT.cod_tema
WHERE T.tema = 'Agricultura';

#3
SELECT A.nom_autor
FROM AUTORES A
INNER JOIN OBRA_AUTOR OA ON A.cod_autor = OA.cod_autor
INNER JOIN OBRA_TEMA OT ON OA.cod_obra = OT.cod_obra
INNER JOIN TEMAS T ON T.cod_tema = OT.cod_tema
WHERE A.nom_autor <> 'Eduardo Mendoza';

#4
SELECT O.COD_OBRA
FROM OBRAS O
INNER JOIN INVENTARIO I ON O.COD_OBRA = I.COD_OBRA
WHERE I.FECHA_RECEPCION < (SELECT FECHA_RECEPCION FROM INVENTARIO WHERE COD_OBRA = 7527);

#5
SELECT A.NOM_AUTOR, COUNT(OA.COD_FUNCION)
FROM AUTORES A
INNER JOIN OBRA_AUTOR OA ON A.COD_AUTOR = OA.COD_AUTOR
INNER JOIN FUNCIONES F ON OA.COD_FUNCION = F.COD_FUNCION
INNER JOIN INVENTARIO I ON OA.COD_OBRA = I.COD_OBRA
WHERE I.FECHA_RECEPCION >= '2000-01-01'
GROUP BY A.NOM_AUTOR
HAVING COUNT(OA.COD_FUNCION) > (
    SELECT AVG(funciones)
    FROM (
        SELECT COUNT(OA2.COD_FUNCION) AS funciones
        FROM OBRA_AUTOR OA2
        INNER JOIN INVENTARIO I2 ON OA2.COD_OBRA = I2.COD_OBRA
        WHERE I2.FECHA_RECEPCION >= '2000-01-01'
        GROUP BY OA2.COD_AUTOR
    ) AS Subquery
)
ORDER BY COUNT(OA.COD_FUNCION) DESC;

#6
SELECT E.nom_editorial
FROM EDITORIALES E
INNER JOIN OBRA_EDITORIAL OE ON E.cod_editorial = OE.cod_editorial
INNER JOIN OBRA_TEMA OT ON OE.COD_OBRA = OT.COD_OBRA
INNER JOIN TEMAS T ON OT.cod_tema = T.cod_tema
INNER JOIN OBRA_AUTOR OA ON OE.COD_OBRA = OA.COD_OBRA
INNER JOIN AUTORES A ON OA.COD_AUTOR = A.COD_AUTOR
WHERE T.TEMA = 'Filosofía' AND A.NOM_AUTOR <> 'Oscar Bierre';

#7
SELECT A.NOM_AUTOR, A.NOTAS
FROM AUTORES A
INNER JOIN OBRA_AUTOR OA ON A.COD_AUTOR = OA.COD_AUTOR
INNER JOIN OBRA_TEMA OT ON OA.COD_OBRA = OT.COD_OBRA
INNER JOIN TEMAS T ON OT.COD_TEMA = T.COD_TEMA
WHERE T.TEMA = 'LITERATURA'
GROUP BY A.NOM_AUTOR, A.NOTAS
HAVING COUNT(A.NOM_AUTOR) > (
    SELECT COUNT(*)
    FROM AUTORES A2
    INNER JOIN OBRA_AUTOR OA2 ON A2.COD_AUTOR = OA2.COD_AUTOR
    INNER JOIN OBRA_TEMA OT2 ON OA2.COD_OBRA = OT2.COD_OBRA
    INNER JOIN TEMAS T2 ON OT2.COD_TEMA = T2.COD_TEMA
    WHERE A2.NOM_AUTOR = 'Gabriela Cañas'
    )
ORDER BY A.NOM_AUTOR

#8
SELECT A.NOM_AUTOR
FROM AUTORES A
INNER JOIN OBRA_AUTOR OA ON OA.`COD_AUTOR` = A.`COD_AUTOR`
INNER JOIN `INVENTARIO` I ON OA.`COD_OBRA` = I.`COD_OBRA`
WHERE I.`FORMA_INGRESO` <> 'CANJE';

#9
SELECT O.`PAIS`,T.`COD_TEMA`, T.`TEMA`, O.`PAGINAS`
FROM OBRAS O
INNER JOIN `OBRA_TEMA` OT ON O.`COD_OBRA` = OT.`COD_OBRA`
INNER JOIN `TEMAS` T ON OT.`COD_TEMA` = T.`COD_TEMA`
GROUP BY O.`PAIS`,T.`COD_TEMA`,T.`TEMA`, O.`PAGINAS`
HAVING AVG(O.`PAGINAS`) > (
    SELECT AVG(O2.`PAGINAS`)
    FROM OBRAS O2
    WHERE O2.PAIS = O.PAIS
);

#10
SELECT A.`NOM_AUTOR`
FROM `AUTORES` A
INNER JOIN `OBRA_AUTOR` OA ON A.`COD_AUTOR` = OA.`COD_AUTOR`
INNER JOIN FUNCIONES F ON OA.`COD_FUNCION` = F.`COD_FUNCION`
INNER JOIN `OBRA_TEMA` OT ON OA.`COD_OBRA` = OT.`COD_OBRA`
INNER JOIN `TEMAS` T ON OT.`COD_TEMA` = T.`COD_TEMA`
GROUP BY A.`NOM_AUTOR`
HAVING COUNT(F.`COD_FUNCION`) = 1 AND COUNT(T.`COD_TEMA`) >1;